#include <stdio.h>
#include <stdbool.h>

#include "hal_data.h"
#include "bsp_uart.h"
#include "apps.h"
#include "ina226.h"
uint8_t volt_state;
#define fine 1
#define short 0
#if (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
bsp_ipc_semaphore_handle_t g_core_start_semaphore =
{
    .semaphore_num = 0
};
#endif
volatile float volt1 = 0.0f;
volatile float volt2 = 0.0f;
    volatile float curr1 = 0.0f;
volatile float curr2 = 0.0f;
/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{

    /* TODO: add your own code here */
    R_IIC_B_MASTER_Open(&g_i2c_master0_ctrl, &g_i2c_master0_cfg);
    INA226_Init(INA226_ADDR_GND_GND); // 0x40
    INA226_Init(INA226_ADDR_GND_VCC); // 0x41
    R_GPT_Open(&g_timer0_ctrl, &g_timer0_cfg);
    R_GPT_Start(&g_timer0_ctrl);
    R_GPT_Open(&g_timer1_ctrl, &g_timer1_cfg);
    R_GPT_Start(&g_timer1_ctrl);
    UART0_Init();
    UART0_SendCmd("page 0");
    FAN_STATE_SET(1,1);
    FAN_STATE_SET(2,1);
    FAN_SPEED_SET(1,25);
    FAN_SPEED_SET(2,25);
    R_BSP_SoftwareDelay (1000, BSP_DELAY_UNITS_MILLISECONDS);
    FAN_STATE_SET(1,0);
    FAN_STATE_SET(2,0);
    R_BSP_SoftwareDelay (1000, BSP_DELAY_UNITS_MILLISECONDS);
    FAN_STATE_SET(1,1);
    FAN_STATE_SET(2,1);
    FAN_SPEED_SET(1,0);
    FAN_SPEED_SET(2,100);
    uint8_t ch1_state = fine;
    uint32_t ch1_recovery_timer = 0;
    uint32_t ch1_startup_ignore = 0;

    uint8_t ch2_state = fine;
    uint32_t ch2_recovery_timer = 0;
    uint32_t ch2_startup_ignore = 0;

    uint32_t blink_counter = 0;
    while (1)
    {
        UART0_RxStaleCheck();

        volt1 = INA226_GetBusVoltage(INA226_ADDR_GND_VCC);
        curr1 = INA226_GetCurrent(INA226_ADDR_GND_VCC);

        volt2 = INA226_GetBusVoltage(INA226_ADDR_GND_GND);
        curr2 = INA226_GetCurrent(INA226_ADDR_GND_GND);
        if (ch1_state == fine)
        {
            if (ch1_startup_ignore > 0) {
                ch1_startup_ignore--;
            }
            else if (volt1 < 9.0f || volt1 > 13.0f || curr1 > 0.09f)
            {
                FAN_STATE_SET(1,0);
                ch1_state = short;
                ch1_recovery_timer = 0;
            }
        }
        else if (ch1_state == short)
        {
            ch1_recovery_timer++;
            if (ch1_recovery_timer >= 30)
            {
                FAN_STATE_SET(1,1);
                ch1_state = fine;
                ch1_startup_ignore = 10;
            }
        }
        if (ch2_state == fine)
        {
            if (ch2_startup_ignore > 0) {
                ch2_startup_ignore--;
            }
            else if (volt2 < 9.0f || volt1 > 13.0f   || curr2 > 0.09f)
            {
                FAN_STATE_SET(2,0);
                ch2_state = short;
                ch2_recovery_timer = 0;
            }
        }
        else if (ch2_state == short)
        {
            ch2_recovery_timer++;
            if (ch2_recovery_timer >= 30)
            {
                FAN_STATE_SET(2,1);
                ch2_state = fine;
                ch2_startup_ignore = 10;
            }
        }

        /* === 串口屏更新 === */
        UART0_UpdateDisplay();

        /* 收到按钮触发 → 仅第1页有效，逐一读取屏幕参数 */
        if (fan_update_request && current_page == 1) {
            fan_update_request = false;

            /* 读 h0.val */
            get_resp_ready = false;
            UART0_SendCmd("get h0.val");
            R_BSP_SoftwareDelay(10, BSP_DELAY_UNITS_MILLISECONDS);
            if (get_resp_ready) { get_resp_ready = false; fan1_duty = get_resp_val; }

            /* 读 h1.val */
            get_resp_ready = false;
            UART0_SendCmd("get h1.val");
            R_BSP_SoftwareDelay(10, BSP_DELAY_UNITS_MILLISECONDS);
            if (get_resp_ready) { get_resp_ready = false; fan2_duty = get_resp_val; }

            /* 读 c0.val */
            get_resp_ready = false;
            UART0_SendCmd("get c0.val");
            R_BSP_SoftwareDelay(10, BSP_DELAY_UNITS_MILLISECONDS);
            if (get_resp_ready) { get_resp_ready = false; fan1_polarity = get_resp_val; }

            /* 读 c1.val */
            get_resp_ready = false;
            UART0_SendCmd("get c1.val");
            R_BSP_SoftwareDelay(10, BSP_DELAY_UNITS_MILLISECONDS);
            if (get_resp_ready) { get_resp_ready = false; fan2_polarity = get_resp_val; }

            /* 应用 */
            FAN_SPEED_SET(1, fan1_duty);
            FAN_SPEED_SET(2, fan2_duty);
            dbg_speed1 = fan1_duty;
            dbg_speed2 = fan2_duty;
        }

        /* === LED 指示 === */
        blink_counter++;

        /* 通道1 LED → P015(红) P500(绿) */
        if (ch1_state == short) {
            R_IOPORT_PinWrite(&g_ioport_ctrl, BSP_IO_PORT_00_PIN_15, BSP_IO_LEVEL_LOW);
            R_IOPORT_PinWrite(&g_ioport_ctrl, BSP_IO_PORT_05_PIN_00, BSP_IO_LEVEL_HIGH);
        } else {
            R_IOPORT_PinWrite(&g_ioport_ctrl, BSP_IO_PORT_00_PIN_15, BSP_IO_LEVEL_HIGH);
            if (curr1 < 0.02f) {
                R_IOPORT_PinWrite(&g_ioport_ctrl, BSP_IO_PORT_05_PIN_00,
                    (blink_counter & 0x08) ? BSP_IO_LEVEL_LOW : BSP_IO_LEVEL_HIGH);
            } else {
                R_IOPORT_PinWrite(&g_ioport_ctrl, BSP_IO_PORT_05_PIN_00, BSP_IO_LEVEL_LOW);
            }
        }

        /* 通道2 LED → P013(红) P014(绿) */
        if (ch2_state == short) {
            R_IOPORT_PinWrite(&g_ioport_ctrl, BSP_IO_PORT_00_PIN_13, BSP_IO_LEVEL_LOW);
            R_IOPORT_PinWrite(&g_ioport_ctrl, BSP_IO_PORT_00_PIN_14, BSP_IO_LEVEL_HIGH);
        } else {
            R_IOPORT_PinWrite(&g_ioport_ctrl, BSP_IO_PORT_00_PIN_13, BSP_IO_LEVEL_HIGH);
            if (curr2 < 0.02f) {
                R_IOPORT_PinWrite(&g_ioport_ctrl, BSP_IO_PORT_00_PIN_14,
                    (blink_counter & 0x08) ? BSP_IO_LEVEL_LOW : BSP_IO_LEVEL_HIGH);
            } else {
                R_IOPORT_PinWrite(&g_ioport_ctrl, BSP_IO_PORT_00_PIN_14, BSP_IO_LEVEL_LOW);
            }
        }
        R_BSP_SoftwareDelay(50, BSP_DELAY_UNITS_MILLISECONDS);
    }
    /* Wake up 2nd core if this is first core and we are inside a multicore project. */
#if (0 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && !BSP_TZ_NONSECURE_BUILD

#if BSP_TZ_SECURE_BUILD
    /* Take semaphore so 2nd core can clear it */
    R_BSP_IpcSemaphoreTake(&g_core_start_semaphore);
#endif

    R_BSP_SecondaryCoreStart();

#if BSP_TZ_SECURE_BUILD
    /* Wait for 2nd core to start and clear semaphore */
    while(FSP_ERR_IN_USE == R_BSP_IpcSemaphoreTake(&g_core_start_semaphore))
    {
        ;
    }
#endif
#endif

#if (1 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
    /* Signal to 1st core that 2nd core has started */
    R_BSP_IpcSemaphoreGive(&g_core_start_semaphore);
#endif


#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
